/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/* 
 * File:   main.cpp
 * Author: David Seitz 
 * Created on May 2, 2020, 7:12pm
 * Purpose: Estimates how much money the east coast devision of a company will generate
 */

//System Level Libraries 
#include <iostream> //I/o Libarary
using namespace std; // Libraries compiled under std

//User Level Libraries

//Global Constants - Science/Math Related
//Conversions, Higher Dimensions

//Function Prototypes

//Execution Begins Here!
int main(int argc, char** argv) {    
    //Variable Declarations
    float divRev; // The percentage of the companys sales generated by the east coast devision
    int totIncm = 8600000; // The total sales by the company this year
    float divIncm=0; // The money made by the east coast division 
    //Variable Initialization
    divRev = 0.58f;
    totIncm = 8600000;
    divIncm = 0;
    //Mapping Process Inputs to Outputs
    divIncm = divRev * totIncm;
    //Display Outputs
    cout<<"The East Coast sales division generates $"<<divIncm;
    //Clean Up
    
    //Exit stage right!
    return 0;
}

